Add nil check for claimRef to avoid segmentation violation error
dell/csm-metrics-powerscale pull request #38
Opened 2023-11-23 14:35 UTC by rajendraindukuri

# Description
- Added a nil check to skip processing pvs without ClaimRef. This will prevent karavi-metrics-powerscale from crashing when there are unbound pv s in clusters
- Enhanced unit tests to cover the same

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1019|

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have inspected the Grafana dashboards to verify the data is displayed properly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?

Tested the scenario using unit tests and it looks good
![image](https://github.com/dell/csm-metrics-powerscale/assets/82365588/5dddd5d4-80ee-43dc-b795-9a070be97e07)

2023-11-24 05:07 UTC, HarishH-DELL approved these changes
LGTM

2023-11-24 08:29 UTC, chimanjain approved these changes

2023-11-28 05:20 UTC, panigs7 approved these changes

2023-11-28 05:24 UTC, rajendraindukuri commented
skip e2e test

2023-11-28 05:25 UTC, rajendraindukuri commented
e2e pass

2023-11-28 10:12 UTC, nitesh3108 commented
e2e pass

2023-11-28 12:00 UTC, gallacher requested changes
Please run e2e against this branch and report the results.

2023-11-28 18:53 UTC, nitesh3108 commented
run e2e test

2023-11-29 14:56 UTC, shefali-malhotra commented
updated e2e results

2023-11-29 14:58 UTC, rajendraindukuri commented
> Please run e2e against this branch and report the results.

@gallacher Updated the e2e test results in the PR description

2023-11-29 15:02 UTC, rajendraindukuri commented
e2e pass

2023-11-29 15:03 UTC, rajendraindukuri commented
e2e pass

2023-11-29 15:03 UTC, gallacher approved these changes

2023-11-29 15:05 UTC, merged